version: '3.3'

services:   
    backend_service:
        build: backend_service
        container_name: backend_service
        ports:
            - "5001:5001"
        expose: 
            - 5001
            
    frontend_service:
        build: frontend_service
        container_name: frontend_service
        ports:
        - "3000:3000"
        links : 
            - "backend_service:backend_service"